doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Accounting:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Accounting/Entity'
                prefix: 'App\Accounting\Entity'
                alias: Accounting
            Classroom:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Classroom/Entity'
                prefix: 'App\Classroom\Entity'
                alias: Classroom
            Configuration:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Configuration/Entity'
                prefix: 'App\Configuration\Entity'
                alias: Configuration
            Pedagogy:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Pedagogy/Entity'
                prefix: 'App\Pedagogy\Entity'
                alias: Pedagogy
            Schooling:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Schooling/Entity'
                prefix: 'App\Schooling\Entity'
                alias: Schooling
            Security:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Security/Entity'
                prefix: 'App\Security\Entity'
                alias: Security
            Student:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Student/Entity'
                prefix: 'App\Student\Entity'
                alias: Student
            Teacher:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Teacher/Entity'
                prefix: 'App\Teacher\Entity'
                alias: Teacher
            Scoring:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Scoring/Entity'
                prefix: 'App\Scoring\Entity'
                alias: Scoring
