vich_uploader:
    db_driver: orm
    mappings:
        student_photo:
            uri_prefix: /media/students
            upload_destination: '%kernel.project_dir%/public/media/students'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
