# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    app_copyright: '&copy; 2019 - PROGESCO'
    app_version: 'v1.0'
    # Titre du projet
    app_title: 'PROGESCO'
    # Hôte LDAP
    ldap_host: '%env(LDAP_HOST)%'
    # Base LDAP
    ldap_baseDn: '%env(LDAP_BASEDN)%'
    # Identifiant de connexion au serveur LDAP
    ldap_identifier: '%env(LDAP_IDENTIFIER)%'
    # Mot de passe de l'identifiant de connexion au serveur LDAP
    ldap_password: '%env(LDAP_PASSWORD)%'
    # Numéro de port du serveur LDAP
    ldap_port: '%env(LDAP_PORT)%'
    # Numéro de version du protocol LDAP
    ldap_protocol_version: 3
    # Permet de définir les groupes de sécurité qui ont accès à l'application. Si pas de restriction
    # laisser le tableau vide
    ldap_authorized_groups: []
    # URL de redirection par défaut après l'authentification
    default_redirection: 'homepage'
    button_alignment: 'd-flex justify-content-center'
    cache_directory: '%kernel.project_dir%/var/cache/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    App\Calendar\Twig\CalendarExtension:
        arguments: ['@service_container']
        public: true
        tags:
            - { name: twig.extension}

    App\Twig\AppExtension:
        public: true
        tags:
            - { name: twig.extension}

    orm.service:
        class: App\Manager\Service\OrmService
        autowire: false
        public: true
        arguments:
            - '@service_container'

    schoolyear.helper:
        class: App\Pedagogy\Helper\SchoolYearHelper
        autowire: false
        public: true
        arguments: ['@service_container']

    gender.service:
        class: App\Configuration\Service\GenderService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    marital_status.service:
        class: App\Configuration\Service\MaritalStatusService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    study.service:
        class: App\Pedagogy\Service\StudyService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    level.service:
        class: App\Pedagogy\Service\LevelService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    grade.service:
        class: App\Pedagogy\Service\GradeService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    schoolyear.service:
        class: App\Pedagogy\Service\SchoolYearService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    courseperiod.service:
        class: App\Pedagogy\Service\CoursePeriodService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    group.service:
        class: App\Pedagogy\Service\GroupService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    speciality.service:
        class: App\Pedagogy\Service\SpecialityService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    subject.service:
        class: App\Pedagogy\Service\TeachingService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    classroom.service:
        class: App\Classroom\Service\ClassroomService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    semester.service:
        class: App\Pedagogy\Service\SemesterService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    course.service:
        class: App\Pedagogy\Service\CourseService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    teacher.service:
        class: App\Teacher\Service\TeacherService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    organization.service:
        class: App\Configuration\Service\OrganizationService
        autowire: true
        public: true
        arguments: ['@service_container','@schoolyear.helper']

    teacher.listener:
        class: App\Teacher\Listener\TeacherListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
            - { name: doctrine.event_listener, event: postPersist, lazy: true }

    App\Student\Listener\StudentListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }

    App\Schooling\Listener\RegistrationListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }

    App\Accounting\Listener\AddFeesFieldSubscriber:
        autowire: false
        public: true

    App\Accounting\Listener\AddFeesFieldScholarshipSubscriber:
        autowire: false
        public: true

    App\Accounting\Form\PaymentType:
        arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker','@schoolyear.helper']
        autowire: false
        public: true
        tags: [form.type]

    App\Accounting\Form\PaymentPlanType:
        arguments: ['@doctrine.orm.entity_manager']
        autowire: false
        public: true
        tags: [form.type]

    App\Accounting\Form\ScholarshipPaymentPlanType:
        arguments: ['@doctrine.orm.entity_manager']
        autowire: false
        public: true
        tags: [form.type]

    App\Accounting\Form\ScholarshipPaymentType:
        arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker','@schoolyear.helper']
        autowire: false
        public: true
        tags: [form.type]

    App\Accounting\Form\TuitionType:
        autowire: false
        public: true
        tags: [form.type]

    App\Schooling\Form\RegistrationType:
        arguments: ['@doctrine.orm.entity_manager','@schoolyear.helper']
        autowire: false
        public: true
        tags: [form.type]

    App\Accounting\Form\ExpenseLineType:
        arguments: ['@doctrine.orm.entity_manager','@schoolyear.helper']
        autowire: false
        public: true
        tags: [form.type]

    App\Scoring\Form\ClassNoteType:
        arguments: ['@doctrine.orm.entity_manager','@schoolyear.helper']
        autowire: false
        public: true
        tags: [form.type]

    App\Accounting\Listener\AddScholarshipAmountFieldSubscriber:
        autowire: false
        public: true

    App\Accounting\Listener\addAmountFieldSubscriber:
        autowire: false
        public: true

    payement.listener:
        class: App\Accounting\Listener\PaymentListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
            - { name: doctrine.event_listener, event: postPersist, lazy: true }
            - { name: doctrine.event_listener, event: preUpdate }

    payementplan.listener:
        class: App\Accounting\Listener\PaymentPlanListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
            - { name: doctrine.event_listener, event: postPersist, lazy: true }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }

    scholarshippayement.listener:
        class: App\Accounting\Listener\ScholarshipPaymentListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
            - { name: doctrine.event_listener, event: postPersist, lazy: true }
            - { name: doctrine.event_listener, event: preUpdate }

    scholarshippayementplan.listener:
        class: App\Accounting\Listener\ScholarshipPaymentPlanListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
            - { name: doctrine.event_listener, event: postPersist, lazy: true }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }

    expenseline.listener:
        class: App\Accounting\Listener\ExpenseLineListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
            - { name: doctrine.event_listener, event: postPersist, lazy: true }
            - { name: doctrine.event_listener, event: preUpdate }

    tuition.listener:
        class: App\Accounting\Listener\TuitionListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
            - { name: doctrine.event_listener, event: postPersist, lazy: true }
            - { name: doctrine.event_listener, event: preUpdate }

    cheque.listener:
        class: App\Accounting\Listener\ChequeListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }

    organization.listener:
        class: App\Configuration\Listener\OrganizationListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
            - { name: doctrine.event_listener, event: postPersist, lazy: true }
            - { name: doctrine.event_listener, event: preUpdate }

    knp_snappy.pdf:
        class: Knp\Snappy\Pdf
        public: true

    Knp\Snappy\Pdf:
        alias: knp_snappy.pdf

    Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface: ~

    Symfony\Component\Security\Core\Security: ~

    App\Security\Service\UserPasswordEncoderService: ~

    Symfony\Component\Security\Core\Authorization\AuthorizationChecker: ~

    Symfony\Component\Serializer\Serializer: ~


    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    #App\Controller\:
    #    resource: '../src/Controller'
    #    tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

knp_paginator:
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'
